
import { useCredibee } from '../hooks/useCredibee';

const translations = {
    en: {
        dashboard: 'Dashboard',
        invoices: 'Invoices',
        receipts: 'Receipts',
        feedback: 'Feedback',
        profile: 'Profile',
        logout: 'Logout',
        hello: 'Hello',
        overview: 'Overview',
        crediScore: 'CrediScore',
        totalRevenue: 'Total Revenue',
        pending: 'Pending',
        totalClients: 'Total Clients',
        revenueAndExpenses: 'Revenue & Expenses',
        recentActivity: 'Recent Activity',
        getFinancialTips: 'Get Financial Tips',
        generatingTips: 'Generating tips...',
        aiPoweredTips: 'AI-Powered Tips',
        allInvoices: 'All Invoices',
        createInvoice: 'Create Invoice',
        editInvoice: 'Edit Invoice',
        clientInfo: 'Client Information',
        clientName: 'Client Name',
        clientEmail: 'Client Email',
        invoiceDetails: 'Invoice Details',
        invoiceNo: 'Invoice #',
        issueDate: 'Issue Date',
        dueDate: 'Due Date',
        items: 'Items',
        description: 'Description',
        quantity: 'Qty',
        price: 'Price',
        total: 'Total',
        addItem: 'Add Item',
        notesAndTerms: 'Notes & Terms',
        subtotal: 'Subtotal',
        tax: 'Tax (12%)',
        saveInvoice: 'Save Invoice',
        updateInvoice: 'Update Invoice',
        status: 'Status',
        actions: 'Actions',
        view: 'View',
        edit: 'Edit',
        allStatuses: 'All Statuses',
        filterByStatus: 'Filter by status',
        searchByClient: 'Search by client or invoice #',
        noInvoicesFound: 'No invoices found.',
        invoice: 'Invoice',
        billedTo: 'Billed To',
        backToInvoices: 'Back to Invoices',
        printOrSave: 'Print / Save PDF',
        sendEmail: 'Send Email',
        markAsPaid: 'Mark as Paid',
        invoiceSent: 'Invoice marked as Sent!',
        invoicePaid: 'Invoice marked as Paid!',
    },
    tl: {
        dashboard: 'Dashboard',
        invoices: 'Mga Invoice',
        receipts: 'Mga Resibo',
        feedback: 'Feedback',
        profile: 'Profile',
        logout: 'Mag-logout',
        hello: 'Kamusta',
        overview: 'Pangkalahatang-ideya',
        crediScore: 'CrediScore',
        totalRevenue: 'Kabuuang Kita',
        pending: 'Nakabinbin',
        totalClients: 'Kabuuang mga Kliyente',
        revenueAndExpenses: 'Kita at Gastusin',
        recentActivity: 'Kamakailang Aktibidad',
        getFinancialTips: 'Kumuha ng Financial Tips',
        generatingTips: 'Gumagawa ng mga tip...',
        aiPoweredTips: 'Mga Tip na mula sa AI',
        allInvoices: 'Lahat ng Invoice',
        createInvoice: 'Gumawa ng Invoice',
        editInvoice: 'I-edit ang Invoice',
        clientInfo: 'Impormasyon ng Kliyente',
        clientName: 'Pangalan ng Kliyente',
        clientEmail: 'Email ng Kliyente',
        invoiceDetails: 'Mga Detalye ng Invoice',
        invoiceNo: 'Invoice #',
        issueDate: 'Petsa ng Pag-isyu',
        dueDate: 'Takdang Petsa',
        items: 'Mga Item',
        description: 'Deskripsyon',
        quantity: 'Dami',
        price: 'Presyo',
        total: 'Kabuuan',
        addItem: 'Magdagdag ng Item',
        notesAndTerms: 'Mga Tala at Tuntunin',
        subtotal: 'Subtotal',
        tax: 'Buwis (12%)',
        saveInvoice: 'I-save ang Invoice',
        updateInvoice: 'I-update ang Invoice',
        status: 'Katayuan',
        actions: 'Mga Aksyon',
        view: 'Tingnan',
        edit: 'I-edit',
        allStatuses: 'Lahat ng Katayuan',
        filterByStatus: 'I-filter ayon sa katayuan',
        searchByClient: 'Maghanap ayon sa kliyente o invoice #',
        noInvoicesFound: 'Walang nahanap na invoice.',
        invoice: 'Invoice',
        billedTo: 'Siningil kay',
        backToInvoices: 'Bumalik sa Mga Invoice',
        printOrSave: 'I-print / I-save ang PDF',
        sendEmail: 'Ipadala sa Email',
        markAsPaid: 'Markahan bilang Bayad',
        invoiceSent: 'Minarkahan ang invoice bilang Ipinadala!',
        invoicePaid: 'Minarkahan ang invoice bilang Bayad!',
    }
};

export const useTranslation = () => {
    const { state } = useCredibee();
    return (key: keyof typeof translations.en) => {
        return translations[state.language][key] || translations.en[key];
    };
};